---
server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: ${SECRET}
    access: ${ACCESS}
    refresh: ${REFRESH}