---
server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
  jpa:
    show-sql: true

  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

security:
  jwt:
    secret: ${SECRET}
    access: ${ACCESS}
    refresh: ${REFRESH}

springdoc:
  override-with-generic-response: false
