version: '3.0'

services:
  app:
    build:
      context: ..
    container_name: task-list
    env_file:
      - ../.env
    depends_on:
      - db
    environment:
      - HOST=${HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8081:8081'

  db:
    image: 'postgres:15.1-alpine'
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5437:5432'
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - ../src/main/resources/db-init:/docker-entrypoint-initdb.d